apiVersion: batch/v1
kind: Job
metadata: 
  name: santander-anagrams-job
spec:
  template: 
    spec:
      containers:
        -
          args: 
            - anagrams.py
          command:
            - phyton
          image: index.docker.io/katmandu25/santander-anagrams:ci
          imagePullPolicy: IfNotPresent
          name: 
          volumeMounts: # Con esto creamos el volumen
            - 
              mountPath: /data 
              name: santander-anagrams-job-volume
              readOnly: true
      initContainers: # Es un contenedor que prepara el camino al contenedor principal. En este caso se descaragará el sist de ficheros
        -
          args:
            - -c
            - ' set -x ; cd /downloads ; rm -f ${filename} ; wget ${url}/${filename} '
          command: 
            - sh
          env:
            -
              name: filename
              valuefrom: 
                -
                  configMapKeyRef: # Usamos el configmap para esta propiedad
                    key: filename # Nombre de la variable
                    name: santander-anagrams-job-cm
            -
              name: url
              valuefrom:
                -
                  secretKeyRef:
                    key: url
                    name: santander-anagrams-secret
          image: busybox
          name: santander-anagrams-job-init-container
          volumeMounts:
           - 
              mountPath: /downloads 
              name: santander-anagrams-job-volume
              readOnly: false
        restartPolicy: Never # Esto solo se ejecuta para descargar y que no se vuelva a ejecutar
        volumes: # Carpeta en el pod // String en la BBDD  // Disco aparte 
          - 
            name: santander-anagrams-job-volume
            emptyDir: {} #PersistentVolumenClaim #ConfigMap son las opciones que hay.
status:{}
  
